-- database/sql/create_analytics_views.sql
CREATE SCHEMA IF NOT EXISTS analytics;
-- 1. Traffic Flow view (cast types)
CREATE OR REPLACE VIEW analytics.traffic_flow AS
SELECT site,
    day,
    NULLIF(date, '')::date AS date,
    NULLIF(start_time, '')::time AS start_time,
    NULLIF(end_time, '')::time AS end_time,
    NULLIF(flow, '')::numeric AS flow,
    NULLIF(flow_pc, '')::numeric AS flow_pc,
    NULLIF(cong, '')::numeric AS cong,
    NULLIF(cong_pc, '')::numeric AS cong_pc,
    NULLIF(dsat, '')::numeric AS dsat,
    NULLIF(dsat_pc, '')::numeric AS dsat_pc,
    "ObjectId" AS object_id,
    __ingested_at
FROM staging.traffic_flow_sdcc_2023_h1;
-- 2. Crash Drivers view (rename columns + cast datetime/numerics)
CREATE OR REPLACE VIEW analytics.crash_drivers AS
SELECT "Report Number" AS report_number,
    "Local Case Number" AS local_case_number,
    "Agency Name" AS agency_name,
    "ACRS Report Type" AS acrs_report_type,
    NULLIF("Crash Date/Time", '')::timestamp AS crash_datetime,
    "Route Type" AS route_type,
    "Road Name" AS road_name,
    "Cross-Street Name" AS cross_street_name,
    "Off-Road Description" AS off_road_description,
    "Municipality" AS municipality,
    "Collision Type" AS collision_type,
    "Weather" AS weather,
    "Surface Condition" AS surface_condition,
    "Light" AS light,
    "Traffic Control" AS traffic_control,
    "Driver Substance Abuse" AS driver_substance_abuse,
    "Driver Distracted By" AS driver_distracted_by,
    "Driver At Fault" AS driver_at_fault,
    "Injury Severity" AS injury_severity,
    "Drivers License State" AS drivers_license_state,
    "Person ID" AS person_id,
    "Vehicle ID" AS vehicle_id,
    NULLIF("Speed Limit", '')::int AS speed_limit,
    "Vehicle Year" AS vehicle_year,
    "Vehicle Make" AS vehicle_make,
    "Vehicle Model" AS vehicle_model,
    NULLIF("Latitude", '')::numeric AS latitude,
    NULLIF("Longitude", '')::numeric AS longitude,
    "Location" AS location,
    __ingested_at
FROM staging.crash_drivers_montgomery_md;
-- 3. Cary Crash Incidents view (cast the key fields)
CREATE OR REPLACE VIEW analytics.crash_incidents AS
SELECT NULLIF(tamainid, '')::bigint AS tamainid,
    location_description,
    NULLIF(lat2, '')::numeric AS lat2,
    NULLIF(lon2, '')::numeric AS lon2,
    -- Keep other coords as optional
    NULLIF(lat, '')::numeric AS lat,
    NULLIF(lon, '')::numeric AS lon,
    NULLIF(crash_date, '')::timestamptz AS crash_date,
    NULLIF(ta_date, '')::date AS ta_date,
    ta_time,
    weather,
    lightcond,
    rdcondition,
    rdsurface,
    trafcontrl,
    rdfeature,
    rdcharacter,
    rdclass,
    rdconfigur,
    contributing_factor,
    vehicle_type,
    vehicle1,
    vehicle2,
    vehicle3,
    vehicle4,
    vehicle5,
    NULLIF(fatality, '')::int AS fatality,
    fatalities,
    injuries,
    NULLIF(possblinj, '')::int AS possible_injury,
    NULLIF(numpassengers, '')::int AS num_passengers,
    NULLIF(numpedestrians, '')::int AS num_pedestrians,
    year,
    month,
    __ingested_at
FROM staging.crash_incidents_cary_nc;